image: jangrewe/gitlab-ci-android

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- ls -al /usr/lib/
- ln -sf /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java /usr/lib/jvm/default-java
- export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

stages:
- build
- test

lintDebug:
  stage: build
  tags:
    - dind
  script:
  - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

assembleDebug:
  stage: build
  tags:
    - dind
  script:
  - ./gradlew assembleDebug

testDebug:
  stage: test
  tags:
    - dind
  script:
  - ./gradlew -Pci --console=plain :app:testDebug